{
  "blocks": [
    {
      "alwaysDisplay": true,
      "blockID": "38c02b6b-4982-4b2d-8890-f415446b32c8",
      "group": 0,
      "instanceID": "5f13b345-8d1c-4a53-93ab-5bea68d08a5a",
      "traitConditions": 0,
      "traits": [],
      "useTraits": false
    },
    {
      "alwaysDisplay": true,
      "blockID": "7f486013-913a-4e4a-9bac-ca3da7071881",
      "group": 0,
      "instanceID": "0d4ab041-0887-4e01-89e7-2bf80c6bc1aa",
      "traitConditions": 0,
      "traits": [],
      "useTraits": false
    },
    {
      "alwaysDisplay": true,
      "blockID": "c2f268d9-0a62-4ff8-8842-a04f7952edf5",
      "group": 0,
      "instanceID": "1e022878-9c93-4dfc-869e-7ef718cb6a7a",
      "traitConditions": 0,
      "traits": [],
      "useTraits": false
    },
    {
      "alwaysDisplay": true,
      "blockID": "aa419886-7422-44d9-8c92-3f3b7ea00174",
      "group": 0,
      "instanceID": "19b2ab8f-1f6e-4354-960c-32bff316037d",
      "traitConditions": 0,
      "traits": [],
      "useTraits": false
    }
  ],
  "id": "17c4b518-2d15-43e7-ab72-18b30cd96043",
  "name": "SafetyInspector-DefaultBlock"
}