{
  "blocks": [
    {
      "alwaysDisplay": true,
      "blockID": "c887c738-eddd-4c4b-8be0-329a5a1e933a",
      "forceScope": 0,
      "group": 1,
      "instanceID": "776774e2-173b-43ee-874b-812dcf24e4cb",
      "traitConditions": 0,
      "traits": [],
      "useTraits": false
    },
    {
      "alwaysDisplay": true,
      "blockID": "64949fce-9233-4a2c-a75a-6649acd38ff4",
      "forceScope": 0,
      "group": 1,
      "instanceID": "6d3bdb7e-5d91-43cc-9c9d-230963f06c63",
      "traitConditions": 0,
      "traits": [],
      "useTraits": false
    },
    {
      "alwaysDisplay": true,
      "blockID": "38fea48b-5768-4c3b-be04-c9990b8882cb",
      "forceScope": 0,
      "group": 1,
      "instanceID": "b725cd87-602f-4eb3-85b9-5d7c0f424b2a",
      "traitConditions": 0,
      "traits": [],
      "useTraits": false
    }
  ],
  "id": "1c873c5f-1092-47c5-999c-6a45bd5e403a",
  "name": "SafetyInspector-Confessions"
}