{
  "blocks": [
    {
      "alwaysDisplay": false,
      "blockID": "8fd912a7-bb9e-454f-bf6b-3b03c691ed13",
      "group": 1,
      "instanceID": "de9f0acf-5b53-44c6-aa9d-ab869e41ddb1",
      "traitConditions": 0,
      "traits": [],
      "useTraits": false
    },
    {
      "alwaysDisplay": true,
      "blockID": "5d7862a2-dafe-47c0-b0cc-f0fb053a008c",
      "group": 0,
      "instanceID": "9d5217fe-9f59-417a-be8c-a7412b96668b",
      "traitConditions": 0,
      "traits": [],
      "useTraits": false
    }
  ],
  "id": "7e2a14e9-7ca3-4a74-80fb-61ce60f32fd9",
  "name": "SafetyInspector-MonkierMessages"
}