{
  "blocks": [
    {
      "alwaysDisplay": true,
      "blockID": "ea24fe89-eb78-484c-9b97-9627952cffd9",
      "group": 0,
      "instanceID": "67ce3b44-27ee-40ff-aaad-4e43da4b30e7",
      "traitConditions": 0,
      "traits": [],
      "useTraits": false
    },
    {
      "alwaysDisplay": true,
      "blockID": "2576244b-e3aa-41e9-949a-9531031ebfa8",
      "group": 0,
      "instanceID": "a918df2e-3b5e-486e-9be7-73d215849a82",
      "traitConditions": 0,
      "traits": [],
      "useTraits": false
    },
    {
      "alwaysDisplay": true,
      "blockID": "423f36c5-cc82-4d2a-9547-23326665e16a",
      "group": 0,
      "instanceID": "b13c9cb6-77ec-4305-91fe-6a2fddd493d6",
      "traitConditions": 0,
      "traits": [],
      "useTraits": false
    },
    {
      "alwaysDisplay": true,
      "blockID": "166a4d97-75bf-4761-b028-490a1d6e62d9",
      "group": 0,
      "instanceID": "ce8cf685-5d7d-4e4d-90c9-4750c7b7e50f",
      "traitConditions": 0,
      "traits": [],
      "useTraits": false
    }
  ],
  "id": "94facd59-cf9d-4e3d-80d2-cca7962480ab",
  "name": "SafetyInspector-VmailBoss"
}